version: '3'
services:
  fasttext:
    command: /bin/bash
    image: xebxeb/fasttext-docker
    volumes:
      - ./fasttext/data/train:/data
      - ./fasttext/data/result:/results
      - ./fasttext/data/test:/mytests
